#!/usr/bin/env bash


echo "Running sync..."

if [ -n "$AWS_BUCKET" ]; then
  cat << EOF > .s3cfg
[default]
access_key = ${AWS_ACCESS_KEY}
secret_key = ${AWS_SECRET_KEY}
EOF
  if [ -d world ]; then
    s3cmd sync world/ s3://${AWS_BUCKET}/world/
    s3cmd sync plugins/ s3://${AWS_BUCKET}/plugins/
  else
    mkdir -p world
    cd world
    s3cmd get --recursive s3://${AWS_BUCKET}/world/
    s3cmd get --recursive s3://${AWS_BUCKET}/plugins/
    cd ..
  fi
  rm .s3cfg
fi

if [ -n "$DROPBOX_ACCESS_TOKEN" ]; then
  cat << EOF > .dropbox_uploader
OAUTH_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
EOF
  if [ -d world ]; then
    tar -czvf "$BACKUP_NAME".tar.gz world world_nether world_the_end plugins
    bin/dropbox_uploader.sh upload "$BACKUP_NAME".tar.gz /
    rm "$BACKUP_NAME".tar.gz
  else
    if bin/dropbox_uploader.sh download /"$BACKUP_NAME".tar.gz
    then
      tar -xzvf "$BACKUP_NAME".tar.gz
      rm "$BACKUP_NAME".tar.gz
    fi
  fi
  rm .dropbox_uploader
fi

# display message inside minecraft
screen -S minecraft -p 0 -X stuff "`printf "say Save sync DONE\r"`"
echo "Sync done..."